# Necessary imports
import sys
import gradio as gr
import spaces

# Local imports
from src.config import device, model_name, sampling, enable_thinking
from src.minicpm.model import load_model
from src.utils.video_processing import encode_video
from src.logger import logging
from src.exception import CustomExceptionHandling


# Model
model = load_model(model_name, device)


@spaces.GPU(duration=120)
def describe_video(
    video: str,
    query: str,
    temperature: float,
    top_p: float,
    top_k: int,
    max_new_tokens: int,
) -> str:
    """
    Generates an answer to a given question based on the provided video and question.

    Args:
        - video (str): The path to the video file.
        - query (str): The question text.
        - temperature (float): The temperature parameter for the model.
        - top_p (float): The top_p parameter for the model.
        - top_k (int): The top_k parameter for the model.
        - max_new_tokens (int): The max tokens to be generated by the model.

    Returns:
        str: The generated answer to the question.
    """
    try:
        # Check if video or query is None
        if not video or not query:
            raise gr.Error("Please provide a video and a question.")

        # Extract frames from the video (unchanged: existing decord-based sampler)
        frames = encode_video(video)

        # Message format for the model
        msgs = [{"role": "user", "content": frames + [query]}]

        # Generate the answer
        answer = model.chat(
            msgs=msgs,
            use_image_id=False,
            max_slice_nums=1,
            use_tts_template=False,
            enable_thinking=enable_thinking,
            do_sample=sampling,
            top_p=top_p,
            top_k=top_k,
            temperature=temperature,
            max_new_tokens=max_new_tokens,
        )

        # Log the successful generation of the answer
        logging.info("Answer generated successfully.")

        # Return the answer
        return answer

    # Handle exceptions that may occur during answer generation
    except Exception as e:
        # Custom exception handling
        raise CustomExceptionHandling(e, sys) from e
